function fmt(m){m=Math.round(m);const h=Math.floor(m/60),mm=m%60;return h?`${h}時間${String(mm).padStart(2,'0')}分`:`${mm}分`;}
const aircraft=document.getElementById('aircraft'),from=document.getElementById('from'),to=document.getElementById('to'),fromMenu=document.getElementById('fromMenu'),toMenu=document.getElementById('toMenu'),result=document.getElementById('result');
const jpSort=(a,b)=>a.localeCompare(b,'ja',{numeric:true,sensitivity:'base'});const aircrafts=[...new Set(ROUTE_STATS.map(x=>x.aircraft))].sort(jpSort);aircraft.innerHTML='<option value="">機種を選択</option>'+aircrafts.map(v=>`<option>${v}</option>`).join('');
const routes=()=>ROUTE_STATS.filter(x=>x.aircraft===aircraft.value);const places=()=>[...new Set(routes().flatMap(x=>[x.a,x.b]))].sort(jpSort);
function empty(){result.innerHTML='<div class="hint">機種を選び、出発地・目的地を文字入力してください。</div>'}
function matches(q){q=q.trim().toLowerCase();const p=places();return q?p.filter(v=>v.toLowerCase().includes(q)).slice(0,30):p.slice(0,30)}
function openMenu(input,menu){const vals=matches(input.value);menu.innerHTML=vals.length?vals.map(v=>`<button type="button" class="menu-item" data-value="${v}">${v}</button>`).join(''):'<div class="menu-empty">候補なし</div>';menu.classList.add('open')}
function bind(input,menu){input.addEventListener('focus',()=>openMenu(input,menu));input.addEventListener('input',()=>{openMenu(input,menu);calc(false)});menu.addEventListener('pointerdown',e=>{const b=e.target.closest('.menu-item');if(!b)return;e.preventDefault();input.value=b.dataset.value;menu.classList.remove('open');input.blur();calc(true)});}
bind(from,fromMenu);bind(to,toMenu);document.addEventListener('pointerdown',e=>{if(!e.target.closest('.combo')){fromMenu.classList.remove('open');toMenu.classList.remove('open')}});
aircraft.addEventListener('change',()=>{from.value='';to.value='';fromMenu.classList.remove('open');toMenu.classList.remove('open');empty()});
function edge(a,b){return routes().find(x=>(x.a===a&&x.b===b)||(x.a===b&&x.b===a))}
function paths(start,goal,maxLegs=6){const adj={};for(const r of routes()){(adj[r.a]??=[]).push([r.b,r]);(adj[r.b]??=[]).push([r.a,r])}const f=[];function dfs(n,seen,legs,total){if(legs.length>maxLegs)return;if(n===goal&&legs.length){f.push({legs:[...legs],total});return}if(legs.length===maxLegs)return;for(const [nx,r] of(adj[n]||[])){if(seen.has(nx))continue;seen.add(nx);legs.push({from:n,to:nx,s:r});dfs(nx,seen,legs,total+r.median);legs.pop();seen.delete(nx)}}dfs(start,new Set([start]),[],0);return f.sort((a,b)=>a.total-b.total||a.legs.length-b.legs.length)}
function cand(p,i){const ns=[p.legs[0].from,...p.legs.map(x=>x.to)];return `<div class="candidate"><div class="candidate-head"><span>候補 ${i+1}</span><strong>約 ${fmt(p.total)}</strong></div><div class="path">${ns.join(' → ')}</div><ul class="legs">${p.legs.map(l=>`<li><span>${l.from} ⇄ ${l.to}</span><strong>約 ${fmt(l.s.median)}</strong><small>実績 ${l.s.count}便</small></li>`).join('')}</ul><div class="sum">純飛行時間 合計 <b>約 ${fmt(p.total)}</b></div></div>`}
function calc(showInvalid=true){const ac=aircraft.value,a=from.value,b=to.value;if(!ac||!a||!b){if(showInvalid)empty();return}const valid=places();if(!valid.includes(a)||!valid.includes(b)){if(showInvalid)result.innerHTML='<div class="hint">表示された候補から地点を選択してください。</div>';return}if(a===b){result.innerHTML='<div class="no-data">出発地と目的地は別の地点を選択してください。</div>';return}const d=edge(a,b);let h=`<div class="route">${a} ⇄ ${b}</div><div class="badge">${ac}</div>`;if(d)h+=`<div class="label">直行実績の空輸時間目安</div><div class="big">約 ${fmt(d.median)}</div><div class="grid"><div><span>実績件数</span><strong>${d.count}便</strong></div><div><span>平均</span><strong>${fmt(d.mean)}</strong></div><div><span>中央値</span><strong>${fmt(d.median)}</strong></div><div><span>実績範囲</span><strong>${fmt(d.min)} ～ ${fmt(d.max)}</strong></div></div>`;const ps=paths(a,b,6).filter(p=>p.legs.length>=2).slice(0,3);if(ps.length)h+=`<div class="subhead">${d?'経由ルートの参考候補':'実績区間から算出した推定ルート'}</div>${ps.map(cand).join('')}`;if(!d&&!ps.length)h+='<div class="no-data">6レグ以内でつながる実績ルートがありません。</div>';h+='<p class="note">同一機種の過去実績を使用。往復は統合し、各レグは中央値です。地上時間は含みません。燃料・航続可否は判定していません。</p>';result.innerHTML=h}
document.getElementById('swap').addEventListener('click',()=>{const a=from.value,b=to.value;from.value=b;to.value=a;calc(true)});empty();
document.getElementById('clearAll').addEventListener('click',function(){from.value='';to.value='';fromMenu.classList.remove('open');toMenu.classList.remove('open');empty();});document.getElementById('refreshPage').addEventListener('click',function(){window.location.reload();});
